# Generated by Django 4.0 on 2022-02-03 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('head0', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField(default=datetime.datetime(2022, 2, 3, 17, 42, 9, 251873, tzinfo=utc))),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
