# Generated by Django 4.0 on 2022-02-03 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_head0',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_head1',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_head2',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 17, 59, 53, 923139, tzinfo=utc)),
        ),
    ]
