# Generated by Django 4.0 on 2022-02-04 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 16, 17, 37, 520365, tzinfo=utc)),
        ),
    ]
