# Generated by Django 4.0 on 2022-02-01 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 17, 59, 4, 509756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 17, 59, 4, 509756, tzinfo=utc)),
        ),
    ]
