# Generated by Django 4.0 on 2022-02-03 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_contact_date_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 17, 42, 9, 241505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 17, 42, 9, 241505, tzinfo=utc)),
        ),
    ]
