# Generated by Django 4.0 on 2022-02-03 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_contact_date_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 18, 3, 40, 663434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 18, 3, 40, 663434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
