# Generated by Django 4.0 on 2022-02-09 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_contact_date_alter_orders_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 5, 2, 34, 289815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 5, 2, 34, 289815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
